config/routes.rb
Ow::Application.routes.draw do
  root 'static_pages#home'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :activities

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/add_activity', to: 'activities#new', via: 'get'

  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  has_many :activity_links, :dependent => :destroy
  default_scope -> { order('created_at DESC') }
  validates :user_id, presence: true
  validates :name, presence: true
  accepts_nested_attributes_for :activity_links, :reject_if => proc { |attributes| attributes[:url].blank? }, :allow_destroy => true
end

app/models/activity_link.rb
class ActivityLink < ActiveRecord::Base
  belongs_to :activity
  validates :activity_id, presence: true
  VALID_URL_REGEX = /.*\.com\z/i
  validates :url, presence: true, format: { with:VALID_URL_REGEX }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :activities
  before_save { email.downcase! }
  before_create :create_remember_token
  validates :display_name, presence: true, length: { maximum: 50, minimum: 3 }, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with:VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :signed_in_user, except: [:show, :index]
  before_action :correct_user_for_activity, only: [:edit, :update, :destroy]

  def show
    @activity = Activity.find(params[:id])
    if @activity.user == current_user
      @can_edit= true
    elsif !current_user.nil?
      if current_user.admin?
        @can_edit = true
      else
        @can_edit = false
      end
    else
      @can_edit = false
    end
  end

  def index
    @activities = Activity.paginate(page: params[:page], per_page: 10)
  end

  def new
    @activity = current_user.activities.build if signed_in?
    @activity.activity_links.build
  end

  def create
    @activity = current_user.activities.build(activity_params)
    if @activity.save
      flash[:success] = "Activity created!"
      redirect_to @activity
    else
      render 'new'
    end
  end

  def edit
    @activity.activity_links.build
  end

  def update
    if @activity.update_attributes(activity_params)
      flash[:success] = "Activity updated"
      redirect_to @activity
    else
      render 'edit'
    end
  end

  def destroy
  end

  private
    def activity_params
      params.require(:activity).permit(:name, :description, :cost, :location,
                                       :activity_links_attributes => [:id, :url, :description, :_destroy])
    end
    def correct_user_for_activity
      @activity = Activity.find(params[:id])
      unless current_user?(@activity.user) || current_user.admin?
        redirect_to(activity_path(@activity), notice: "You do not have permission to modify this activity.")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private
    def not_already_signed_in
      if signed_in?
        redirect_to root_url, notice: "Already signed in as '#{current_user.display_name}'"
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :not_already_signed_in, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      #Sign in the user and redirect to user page
      sign_in user
      redirect_back_or user
    else
      #Create error message and re-render signin form
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end
  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :index]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]
  before_action :not_already_signed_in, only: [:new, :create]

  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 20)
  end

  def edit
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "New account created successfully!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @activities = @user.activities.paginate(page: params[:page], per_page: 5)
  end

  private
    def user_params
      params.require(:user).permit(:display_name, :email, :password, :password_confirmation)
    end

    #Before filters
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Orange Walrus"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_activity.html.erb
<li>
  <%= link_to(activity_path(activity), class:"list-group-item ow-border-blue", style:"border-width:0.2em; margin-bottom: 0.5em" ) do %>
      <%= activity.name %>
  <% end %>
</li>

app/views/activities/_activity_link_fields.html.erb
<li>
  <%= builder.label :url, "Link to additional info" %>
  <%= builder.text_field :url, placeholder: "www.activity-page.com" %>
  <%= builder.label :description, "Description of link" %>
  <%= builder.text_field :description, placeholder: "The main information page for this activity." %>
  <%= builder.check_box :_destroy %>
  <%= builder.label :_destroy, "Remove Activity Link" %>
</li>

app/views/activities/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%=  f.label :name %>
<%=  f.text_field :name, placeholder: "Enter Activity Name (eg. 'Co-ed baseball league')..." %>

<%= f.label :description %>
<%= f.text_area :description, placeholder: "Enter a short description of the activity..." %>

<%= f.label :cost %>
<%= f.text_area :cost, placeholder: "How much does the activity cost?" %>

<%= f.label :location %>
<%= f.text_area :location, placeholder: "Where is the activity located?" %>

<ul class="activity-links">
  <%= f.fields_for :activity_links do |builder| %>
    <%= render partial: 'activity_link_fields', locals: { :builder => builder} %>
  <% end %>
</ul>

app/views/activities/edit.html.erb
<% provide(:title, "Edit Activity") %>
<h1>Edit Activity</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@activity) do |f| %>
        <%= render partial: 'fields', locals: { :f => f} %>
        <%= f.submit "Update Activity", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/activities/index.html.erb
<% provide(:title, "Activity Index") %>
<h3>Browsing Activities</h3>

<ul class="activities list-group" style="margin-top:1em">
  <%= render @activities %>
</ul>

<%= will_paginate %>

app/views/activities/new.html.erb
<% provide(:title, 'Add Activity') %>
<h1>New Activity</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@activity) do |f| %>
        <%= render partial: 'fields', locals: { :f => f} %>
        <%= f.submit "Create Activity", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/activities/show.html.erb
<% provide(:title, @activity.name) %>
<p>Name: <%= @activity.name %></p>
<p>Description: <%= @activity.description %></p>
<p>Cost: <%= @activity.cost %></p>
<p>Location: <%= @activity.location %></p>
<% if @activity.activity_links.any? %>
    <p>Links to Additional Information: </p>
    <ul class="activity-links">
      <% @activity.activity_links.each do |al| %>
        <li><%= "#{al.url} (#{al.description})"%></li>
      <% end %>
    </ul>
<% end %>

<% if @can_edit %>
    <%= link_to("Edit", edit_activity_path(@activity)) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= favicon_link_tag %>
</head> <body>
    <div class="container">
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <% if signed_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li class="active"><%=  link_to "Sign in", signin_path %></li>
              <li><%=  link_to "Sign up", signup_path %></li>
          <% end %>
        </ul>
        <h2 class="text-muted">
            <%= link_to(root_path, style: "text-decoration:none" ) do %>
                <span class="ow-orange">orange</span><span class="ow-blue">walrus</span>
            <% end %>
        </h2>
      </div>
      <%= debug(params) if Rails.env.development? %>
      <%=  %>
      <%= yield %>
      <div class="footer">
        <p>&copy; Orange Walrus</p>
      </div>

    </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="jumbotron">
  <p class="lead">Find something to do.</p>
  <p><%= link_to "Find Activities", activities_path, class: 'btn btn-lg btn-blue' %></p>
  <p class="lead">Share something to do.</p>
  <p><%= link_to "Add Activities", add_activity_path, class: 'btn btn-lg btn-orange' %></p>
</div>
<div class="center">
  <%= image_tag "ow_bg.png", class: 'logo center' %>
</div>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%=  f.label :display_name %>
<%=  f.text_field :display_name %>

<%=  f.label :email  %>
<%=  f.text_field :email %>

<%=  f.label :password, "Password" %>
<%=  f.password_field :password %>

<%=  f.label :password_confirmation, "Confirm Password" %>
<%=  f.password_field :password_confirmation  %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.display_name, user %>
  <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
            data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%=  render partial: 'fields', locals: { :f => f} %>
        <%=  f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%=  will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%=  render partial: 'fields', locals: { :f => f} %>
        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.display_name) %>
<%= @user.display_name %>, <%= @user.email %>

<div class="span8">
  <% if @user.activities.any? %>
      <h3>Activities (<%= @user.activities.count %>)</h3>
      <ol class="activities">
        <%= render @activities %>
      </ol>
      <%= will_paginate @activities %>
  <% end %>
</div>